version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - ENV=production
    ports:
      - "8088:80"  # Map port 8088 on the host to port 80 inside the container
    depends_on:
      - backend
    networks:
      - miles_network

  backend:
    build: ./backend
    ports:
      - "8090:8090"  # Map port 8090 on the host to port 80 inside the container
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/milesdb
      - NODE_ENV=production
    networks:
      - miles_network

  mongo:
    image: mongo:latest
    container_name: miles-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - miles_network

volumes:
  mongo_data:

networks:
  miles_network:
    driver: bridge
